### ISSUE TITLE
gossip: main thread panic when run via `brew test`

### ISSUE THREAD

**Issue by badonyx** [nostorg/homebrew-nostr#6]
Trying to make a better test assertion for the gossip formula but running it through `brew test` causes the main thread to panic so I cannot get any proper output.

New test:

```ruby
    input_json = '{"id":"b9fead6eef87d8400cbc1a5621600b360438affb9760a6a043cc0bddea21dab6","kind":1,"pubkey":"82341f882b6eabcd2ba7f1ef90aad961cf074af15b9ef44a09f9d2a8fbfbe6a2","created_at":1676161639,"content":"this is going to work","tags":[],"sig":"76d19889a803236165a290fa8f3cf5365af8977ee1e002afcfd37063d1355fc755d0293d27ba0ec1c2468acfaf95b7e950e57df275bb32d7a4a3136f8862d2b7"}'
    # ENV["RUST_BACKTRACE"] = "full"
    assert_match "Valid event", shell_output("#{bin}/gossip verify_json #{input_json}", 101)
```

Output:

```
❯ brew test gossip
==> Testing nostorg/nostr/gossip
==> /opt/homebrew/Cellar/gossip/0.8.0/bin/gossip verify_json {"id":"b9fead6eef87d8400cbc1a5621600b360438affb9760a6a043cc0bddea21
thread 'main' panicked at 'I/O Error: No such file or directory (os error 2)', src/globals.rs:136:23
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error: nostorg/nostr/gossip: failed
An exception occurred within a child process:
  Minitest::Assertion: Expected /Valid\ event/ to match "".
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/minitest-5.20.0/lib/minitest/assertions.rb:183:in `assert'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/minitest-5.20.0/lib/minitest/assertions.rb:295:in `assert_match'
/opt/homebrew/Library/Taps/nostorg/homebrew-nostr/Formula/gossip.rb:44:in `block in <class:Gossip>'
/opt/homebrew/Library/Homebrew/formula.rb:2490:in `block (3 levels) in run_test'
/opt/homebrew/Library/Homebrew/extend/kernel.rb:499:in `with_env'
/opt/homebrew/Library/Homebrew/formula.rb:2489:in `block (2 levels) in run_test'
/opt/homebrew/Library/Homebrew/formula.rb:1053:in `with_logging'
/opt/homebrew/Library/Homebrew/formula.rb:2488:in `block in run_test'
/opt/homebrew/Library/Homebrew/mktemp.rb:75:in `block in run'
/opt/homebrew/Library/Homebrew/mktemp.rb:75:in `chdir'
/opt/homebrew/Library/Homebrew/mktemp.rb:75:in `run'
/opt/homebrew/Library/Homebrew/formula.rb:2782:in `mktemp'
/opt/homebrew/Library/Homebrew/formula.rb:2482:in `run_test'
/opt/homebrew/Library/Homebrew/test.rb:44:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
/opt/homebrew/Library/Homebrew/test.rb:48:in `<main>'
```

With `RUST_BACKTRACE=full`:

```
❯ brew test gossip
==> Testing nostorg/nostr/gossip
==> /opt/homebrew/Cellar/gossip/0.8.0/bin/gossip verify_json {"id":"b9fead6eef87d8400cbc1a5621600b360438affb9760a6a043cc0bddea21
thread 'main' panicked at 'I/O Error: No such file or directory (os error 2)', src/globals.rs:136:23
stack backtrace:
   0:        0x105745078 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4ad3e9225f7521e9
   1:        0x10577f120 - core::fmt::write::hd596d2031660b392
   2:        0x105758cac - std::io::Write::write_fmt::h2c992930f1478641
   3:        0x105744e80 - std::sys_common::backtrace::print::haf9902f09b134a96
   4:        0x1057598fc - std::panicking::default_hook::{{closure}}::h7808808df9612efd
   5:        0x105759668 - std::panicking::default_hook::h01526266ddbcf080
   6:        0x105759e84 - std::panicking::rust_panic_with_hook::hf80c108ff425fa61
   7:        0x1057459e0 - std::panicking::begin_panic_handler::{{closure}}::h5df3e10b49e527bd
   8:        0x10574516c - std::sys_common::backtrace::__rust_end_short_backtrace::hece657cf8f4082b7
   9:        0x105759aa4 - _rust_begin_unwind
  10:        0x1057d40e8 - core::panicking::panic_fmt::hb9fc09aa98cf5e3e
  11:        0x104b86704 - std::sync::once::Once::call_once::{{closure}}::hfddb6906d3e2d3ee
  12:        0x1057d3884 - std::sys_common::once::queue::Once::call::hf8f1076e0eb7cb95
  13:        0x104d96360 - gossip::main::hc5b10e900d60ebd4
  14:        0x104c48218 - std::sys_common::backtrace::__rust_begin_short_backtrace::h90653b36f1b5a2b4
  15:        0x104b36824 - std::rt::lang_start::{{closure}}::hc44453143ca16be3
  16:        0x1057581bc - std::rt::lang_start_internal::h3938ec785a4c1449
  17:        0x104d975d0 - _main
Error: nostorg/nostr/gossip: failed
An exception occurred within a child process:
  Minitest::Assertion: Expected /Valid\ event/ to match "".
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/minitest-5.20.0/lib/minitest/assertions.rb:183:in `assert'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/minitest-5.20.0/lib/minitest/assertions.rb:295:in `assert_match'
/opt/homebrew/Library/Taps/nostorg/homebrew-nostr/Formula/gossip.rb:45:in `block in <class:Gossip>'
/opt/homebrew/Library/Homebrew/formula.rb:2490:in `block (3 levels) in run_test'
/opt/homebrew/Library/Homebrew/extend/kernel.rb:499:in `with_env'
/opt/homebrew/Library/Homebrew/formula.rb:2489:in `block (2 levels) in run_test'
/opt/homebrew/Library/Homebrew/formula.rb:1053:in `with_logging'
/opt/homebrew/Library/Homebrew/formula.rb:2488:in `block in run_test'
/opt/homebrew/Library/Homebrew/mktemp.rb:75:in `block in run'
/opt/homebrew/Library/Homebrew/mktemp.rb:75:in `chdir'
/opt/homebrew/Library/Homebrew/mktemp.rb:75:in `run'
/opt/homebrew/Library/Homebrew/formula.rb:2782:in `mktemp'
/opt/homebrew/Library/Homebrew/formula.rb:2482:in `run_test'
/opt/homebrew/Library/Homebrew/test.rb:44:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
/opt/homebrew/Library/Homebrew/test.rb:48:in `<main>'
```

**Comment by badonyx** [comment]
Potential blocker on getting gossip included in `homebrew-core` (https://github.com/Homebrew/homebrew-core/pull/144330). @mikedilger any ideas? Seems like a homebrew/ruby issue but it could be an indication that gossip is doing something nonstandard that might be handled differently.

**Comment by mikedilger** [comment]
v0.8.0 is commit c9bb3704e94e105d7cf97de67e89ccf7f01ef69b so line numbers refer to that.

globals.rs:136 is a failure to create Storage. The error is "no such file or directory."

Storage uses profile.rs to sort out the directory, which has some ways you can force it. For example, you can set environment variable GOSSIP_DIR to some testing directory, and even set GOSSIP_PROFILE to a subdirectory to run multiple profiles.

**Comment by badonyx** [comment]
Thanks for the tip. Was very hopeful this would do the trick, setting `GOSSIP_DIR` with the appropriate function from homebrew.

```ruby
    ENV["GOSSIP_DIR"] = "#{testpath}"
```

Unfortunately there was no change.

**Comment by badonyx** [comment]
How do I find what file path it is trying to access?

**Comment by mikedilger** [comment]
This is the base dir if you don't override it:  https://docs.rs/dirs/latest/dirs/fn.data_dir.html
Under that it should create a "gossip" directory.

On the 'unstable' branch I just pushed a commit that will log an error with the directory it was trying if this error occurs.

**Comment by badonyx** [comment]
Should be good now, thanks mike.

**Comment by badonyx** [comment]
Oh yeah -- you might like to know that the error was actually occurring in `Profile::new` at https://github.com/mikedilger/gossip/blob/f2dded420e6790cbcc6f421801d153d475b329f3/src/profile.rs#L38
```
let data_dir = normalize(data_dir)?;
```
before `GOSSIP_DIR` is even checked. It was due to the `data_dir` not existing in the `testpath` (and me not knowing exactly what directories needed to be created). 

Not sure why it does not throw an error at `let data_dir = dirs::data_dir()`. Also I'm not super familiar with rust but isn't it supposed to be forbidden to re-define a variable unless it is `mut`?

**Comment by mikedilger** [comment]
> Also I'm not super familiar with rust but isn't it supposed to be forbidden to re-define a variable unless it is mut?

If you redefine the same var name, it replaces it.  By using 'let', it creates a new var of the same name and the old var goes out of scope.  Without the 'let' it would indeed complain that data_dir is not mutable.

**Comment by mikedilger** [comment]
> Not sure why it does not throw an error at let data_dir = dirs::data_dir()

dirs::data_dir() doesn't even look at the filesystem.  normalize() does.
